services:
  backend:
    image: salehaa/devlog-backend:v1
    container_name: devlog-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/firebase-service-account.json:/app/firebase-service-account.json:ro
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    image: salehaa/devlog-frontend:v1
    container_name: devlog-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: devlog-mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
# environment:
#   MONGO_INITDB_DATABASE: devlog_db

volumes:
  mongo_data:
