const envConfig = {
    VITE_BACKEND_API_BASE_URL: '__VITE_BACKEND_API_BASE_URL__',
    VITE_FIREBASE_API_KEY: '__VITE_FIREBASE_API_KEY__',
    VITE_FIREBASE_AUTH_DOMAIN: '__VITE_FIREBASE_AUTH_DOMAIN__',
    VITE_FIREBASE_PROJECT_ID: '__VITE_FIREBASE_PROJECT_ID__',
    VITE_FIREBASE_STORAGE_BUCKET: '__VITE_FIREBASE_STORAGE_BUCKET__',
    VITE_FIREBASE_MESSAGING_SENDER_ID: '__VITE_FIREBASE_MESSAGING_SENDER_ID__',
    VITE_FIREBASE_APP_ID: '__VITE_FIREBASE_APP_ID__',
};

export default envConfig;
