name: Build and Push Docker Images

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: Get short commit SHA
      id: vars
      run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/devlog-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/devlog-backend:${{ env.SHORT_SHA }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/devlog-frontend:latest
          ${{ secrets.DOCKER_USERNAME }}/devlog-frontend:${{ env.SHORT_SHA }}

    - name: Update docker-compose.yml with commit SHA tags
      run: |
        sed -i "s|devlog-backend:latest|devlog-backend:${SHORT_SHA}|g" compose.yml
        sed -i "s|devlog-frontend:latest|devlog-frontend:${SHORT_SHA}|g" compose.yml
    
    - name: Commit and push updated compose.yml
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add compose.yml
        git commit -m "Update compose.yml with image tags for ${{ env.SHORT_SHA }}" || echo "No changes to commit"
        git push
